# Generated by Django 2.2.6 on 2019-10-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_company', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('title_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.PreviousFirm')),
            ],
        ),
    ]
