# Generated by Django 2.2.5 on 2019-10-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20191007_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_para1', models.TextField()),
                ('bio_para2', models.TextField()),
                ('bio_para3', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='previoustitle',
            name='title_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firms', to='helloworld.PreviousFirm'),
        ),
    ]
