# Generated by Django 2.2.5 on 2019-10-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20191009_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course_desc',
            field=models.TextField(default='xxx'),
            preserve_default=False,
        ),
    ]
