# Generated by Django 2.2.5 on 2019-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_education_course_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
