# Generated by Django 2.2.5 on 2019-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_auto_20191015_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
